## Annotated Bibliography

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE)
library(tinytex)
library(ggplot2)
library(dplyr)
library(tidyr)
library(rlang)
library(usethis)
library(bookdown)
library(knitr)
library(rmarkdown)
library(spelling)
```

Beca, Gabrielle, Leonie E. Valentine, Mauro Galetti, and Richard J. Hobbs. “Ecosystem Roles and Conservation Status of Bioturbator Mammals.” Mammal Review 52, no. 2 (April 2022): 192–207. <https://doi.org/10.1111/mam.12269>.

-   Review on the global distrobution and conservation/endangered status of bioturbator mammals. Great map showing global abundance, mostly in subtropical and temperate grasslands. 22% of non-flying land-dwalling mammal species regularly perform bioturbation.
-   This data would be fascinating to look more into. Especially if there was invertebrate data to pair it with. As is, this is a good source for the widespread distribution of bioturbators, and shows that at least globally they are sensitive to moisture.
-   Present a table on with some examples of ecological roles. Could be useful.

Bétard, François. “Insects as Zoogeomorphic Agents: An Extended Review.” Earth Surface Processes and Landforms 46, no. 1 (2021): 89–109. <https://doi.org/10.1002/esp.4944>.

Blouin, M., M. E. Hodson, E. A. Delgado, G. Baker, L. Brussaard, K. R. Butt, J. Dai, et al. “A Review of Earthworm Impact on Soil Function and Ecosystem Services.” European Journal of Soil Science 64, no. 2 (April 2013): 161–82. <https://doi.org/10.1111/ejss.12025>.

Canti, M.G. “Earthworm Activity and Archaeological Stratigraphy: A Review of Products and Processes.” Journal of Archaeological Science 30, no. 2 (February 2003): 135–48. <https://doi.org/10.1006/jasc.2001.0770>.

Chang, Chih-Han, Marie L. C. Bartz, George Brown, Mac A. Callaham, Erin K. Cameron, Andrea Dávalos, Annise Dobson, et al. “The Second Wave of Earthworm Invasions in North America: Biology, Environmental Impacts, Management and Control of Invasive Jumping Worms.” Biological Invasions 23, no. 11 (November 2021): 3291–3322. <https://doi.org/10.1007/s10530-021-02598-1>.

-   Review the impacts of jumping worms on soils. Probably not usable in this review, unless as a case study of the contrast between two earthworm groups.

Chiriac, Luiza Silvia, and Dumitru T Murariu. “THE ECOLOGICAL ROLE OF SOME FUNCTIONAL GROUPS OF INVERTEBRATES – A REVIEW,” n.d.

Corenblit, Dov, Andreas C.W. Baas, Gudrun Bornette, José Darrozes, Sébastien Delmotte, Robert A. Francis, Angela M. Gurnell, Frédéric Julien, Robert J. Naiman, and Johannes Steiger. “Feedbacks between Geomorphology and Biota Controlling Earth Surface Processes and Landforms: A Review of Foundation Concepts and Current Understandings.” Earth-Science Reviews 106, no. 3–4 (June 2011): 307–31. <https://doi.org/10.1016/j.earscirev.2011.03.002>.

-   Review of the linkages between organisms and landscape evolution. Organims are constrained by env parameters, driving evolution, but simultaneously shape the landscape, creating a feedback process.

-   Animal architects are keystone species. A little heavy on genetics.

-   This will but useful in talking about time: how organisms and landscapes co-evolve.

Corenblit, Dov, Bruno Corbara, and Johannes Steiger. “Biogeomorphological Eco-Evolutionary Feedback between Life and Geomorphology: A Theoretical Framework Using Fossorial Mammals.” The Science of Nature 108, no. 6 (December 2021): 55. <https://doi.org/10.1007/s00114-021-01760-y>.

Corenblit, Dov, Eric Tabacchi, Johannes Steiger, and Angela M. Gurnell. “Reciprocal Interactions and Adjustments between Fluvial Landforms and Vegetation Dynamics in River Corridors: A Review of Complementary Approaches.” Earth-Science Reviews 84, no. 1–2 (September 2007): 56–86. <https://doi.org/10.1016/j.earscirev.2007.05.004>.

Eckmeier, Eileen, Renate Gerlach, Ernst Gehrt, and Michael W.I. Schmidt. “Pedogenesis of Chernozems in Central Europe — A Review.” Geoderma 139, no. 3–4 (May 2007): 288–99. <https://doi.org/10.1016/j.geoderma.2007.01.009>.

Eijsackers, H. “Earthworms as Colonizers of Natural and Cultivated Soil Environments.” Applied Soil Ecology 50 (October 2011): 1–13. <https://doi.org/10.1016/j.apsoil.2011.07.008>.

Feller, Christian, George G Brown, Eric Blanchart, Pierre Deleporte, and Sergey S Chernyanskii. “Charles Darwin, Earthworms and the Natural Sciences: Various Lessons from Past to Future.” Agriculture, Ecosystems & Environment 99, no. 1–3 (October 2003): 29–49. [https://doi.org/10.1016/S0167-8809(03)00143-9](https://doi.org/10.1016/S0167-8809(03)00143-9){.uri}.

Folgarait, Patricia J. “Ant Biodiversity and Its Relationship to Ecosystem Functioning: A Review.” Biodiversity and Conservation 7, no. 9 (September 1998): 1221–44. <https://doi.org/10.1023/A:1008891901953>.

Gabet, Emmanuel J., O.J. Reichman, and Eric W. Seabloom. “The Effects of Bioturbation on Soil Processes and Sediment Transport.” Annual Review of Earth and Planetary Sciences 31, no. 1 (May 2003): 249–73. <https://doi.org/10.1146/annurev.earth.31.100901.141314>.

Harit, Ajay, Rashmi Shanbhag, Ekta Chaudhary, Sougueh Cheik, and Pascal Jouquet. “Properties and Functional Impact of Termite Sheetings.” Biology and Fertility of Soils 53, no. 7 (October 2017): 743–49. <https://doi.org/10.1007/s00374-017-1228-7>.

Johnson, D. L., J. E. J. Domier, and D. N. Johnson. “Reflections on the Nature of Soil and Its Biomantle.” Annals of the Association of American Geographers 95, no. 1 (March 1, 2005): 11–31. <https://doi.org/10.1111/j.1467-8306.2005.00448.x>.

Jouquet, Pascal, Jens Dauber, Jan Lagerlöf, Patrick Lavelle, and Michel Lepage. “Soil Invertebrates as Ecosystem Engineers: Intended and Accidental Effects on Soil and Feedback Loops.” Applied Soil Ecology 32, no. 2 (June 2006): 153–64. <https://doi.org/10.1016/j.apsoil.2005.07.004>.

Lavelle, Patrick. “Soil Function in a Changing World: The Role of Invertebrate Ecosystem Engineers,” 1997. Maire, O, P Lecroart, F Meysman, R Rosenberg, J Duchêne, and A Grémare. “Quantification of Sediment Reworking Rates in Bioturbation Research: A Review.” Aquatic Biology 2, no. 3 (June 19, 2008): 219–38. <https://doi.org/10.3354/ab00053>.

Mason, Richard J., and Harry Sanders. “Invertebrate Zoogeomorphology: A Review and Conceptual Framework for Rivers.” WIREs Water 8, no. 5 (September 2021): e1540. <https://doi.org/10.1002/wat2.1540>.

-   Claims Zoomorphology as a field is specifically for fluvial landscapes / rivers? Reviews of the roles of various aquatic organisms in bioturbating and -eroding stream banks and beds. Interesting horizontal erosion framework.

-   Body size is a primary driver of organism impact: both magnitude and direction. Larger organisms occupy more space individually, so likely have more localized impacts (greater burrow spacing). I wonder if anyone has done a study comparing burrow spacing to organism size. However, organism size also determines the size of particles they can move.

-   What if I desribe the 4(ish) sections of my conceptual model, then took a moment to discuss why there is such diversity. There is also an opperunity to disucss direction (i.e. direciton of pedogenesis).

-   This is a good example of a conceptual model being put forward to help us understand organisms better. Good note on invasive species.

McBrearty, Sally. “Consider the Humble Termite: Termites as Agents of Post-Depositional Disturbance at African Archaeological Sites.” Journal of Archaeological Science 17, no. 2 (March 1990): 111–43. [https://doi.org/10.1016/0305-4403(90)90054-9](https://doi.org/10.1016/0305-4403(90)90054-9){.uri}.

Meysman, F, J Middelburg, and C Heip. “Bioturbation: A Fresh Look at Darwin’s Last Idea.” Trends in Ecology & Evolution 21, no. 12 (December 2006): 688–95. <https://doi.org/10.1016/j.tree.2006.08.002>.

Muvengwi, Justice, and Edward T. F. Witkowski. “Cascading Effects of Termite Mounds in African Savannas.” New Zealand Journal of Botany 58, no. 3 (July 2, 2020): 167–93. <https://doi.org/10.1080/0028825X.2020.1767162>.

Nascimento, Diego Luciano, Mariane Chiapini, Pablo Vidal-Torrado, Jonathan D. Phillips, Francisco Sérgio Bernardes Ladeira, Diego Fernandes Terra Machado, Roberto Da Silva Camargo, and Everton Vinícius Valezio. “The Underestimated Role of Leaf-Cutting Ants in Soil and Geomorphological Development in Neotropical America.” Earth-Science Reviews 248 (January 2024): 104650. <https://doi.org/10.1016/j.earscirev.2023.104650>.

-   A review of the activities of leaf cutter ants (LCA) in neoamerica. Create both constructional (surface) and excavational (subsurface) landforms that both have impact landscape evolution (e.g. filled burrows contribute to soil creep). They perform both biomixing AND biosorting simultaneously, depending on the parent material.

-   Actions on the landscape are cumulative. Hundreds of colonies over thousands of years. Some intentional constructions: mounds are built to reduce flooding of burrows.

-   Really great figure that represents the different sources of downward-moving material.

-   This is great evidence of cumulative impacts to support a conceptual model.

Palmer, Bryony J., Leonie E. Valentine, Manda Page, and Richard J. Hobbs. “Translocations of Digging Mammals and Their Potential for Ecosystem Restoration: A Review of Goals and Monitoring Programmes.” Mammal Review 50, no. 4 (October 2020): 382–98. <https://doi.org/10.1111/mam.12208>.

-   Reviews historical to current translocations of digging mammals in Australia

-   Could be used a proof that they are recognized as important to ecosystem restoration.

Pawlik, Łukasz, Jonathan D. Phillips, and Pavel Šamonil. “Roots, Rock, and Regolith: Biomechanical and Biochemical Weathering by Trees and Its Impact on Hillslopes—A Critical Literature Review.” Earth-Science Reviews 159 (August 2016): 142–59. <https://doi.org/10.1016/j.earscirev.2016.06.002>.

Pawlik, Łukasz, and Pavel Šamonil. “Soil Creep: The Driving Factors, Evidence and Significance for Biogeomorphic and Pedogenic Domains and Systems – A Critical Literature Review.” Earth-Science Reviews 178 (March 2018): 257–78. <https://doi.org/10.1016/j.earscirev.2018.01.008>.

-   Review of the historical development of organism-driven soil creep. Great figures. Thorough information on the role of organisms

Reichman, O.J., and Eric W. Seabloom. “The Role of Pocket Gophers as Subterranean Ecosystem Engineers.” Trends in Ecology & Evolution 17, no. 1 (January 2002): 44–49. [https://doi.org/10.1016/S0169-5347(01)02329-1](https://doi.org/10.1016/S0169-5347(01)02329-1){.uri}.

Reinhardt, Liam, Douglas Jerolmack, Brad J. Cardinale, Veerle Vanacker, and Justin Wright. “Dynamic Interactions of Life and Its Landscape: Feedbacks at the Interface of Geomorphology and Ecology.” Earth Surface Processes and Landforms 35, no. 1 (January 2010): 78–101. <https://doi.org/10.1002/esp.1912>.

Schneider, Anne-Kathrin, and Boris Schröder. “Perspectives in Modelling Earthworm Dynamics and Their Feedbacks with Abiotic Soil Properties.” Applied Soil Ecology 58 (July 2012): 29–36. <https://doi.org/10.1016/j.apsoil.2012.02.020>.

Sharma, D. K., S. Tomar, and D. Chakraborty. “Role of Earthworm in Improving Soil Structure and Functioning.” Current Science 113, no. 06 (September 25, 2017): 1064. <https://doi.org/10.18520/cs/v113/i06/1064-1071>.

Stockmann, Uta, Budiman Minasny, and Alexander McBratney. “Advances in Agronomy Quantifying Processes of Pedogenesis.” In Advances in Agronomy, 113:1–74. Elsevier, 2011. <https://doi.org/10.1016/B978-0-12-386473-4.00001-4>.

Übernickel, Kirstin, Jaime Pizarro-Araya, Susila Bhagavathula, Leandro Paulino, and Todd A. Ehlers. “Reviews and Syntheses: Composition and Characteristics of Burrowing Animals along a Climate and Ecological Gradient, Chile.” Biogeosciences 18, no. 20 (October 18, 2021): 5573–94. <https://doi.org/10.5194/bg-18-5573-2021>.

-   A very thorough review (1000+ sources) on the behaviors and impacts of bioturbators, vertebrates and invertebrates, in Chile. Acknowledges prior studes are heterogenious in methods, hard to estimate impact on the landscape and do not cover other biomes besides NA. We need a way to estimate the aggreagate impact of animals on the landscape.

-   Covers variability in excavation rates, tunnel diameter (sorting implications?), burrow depth, geographic distribution. Touches on the need for seasonality.

-   This can be used for a lot. Great evidence for the variability and different axes of animal activity, and also highlights the need for more thorough, consistent data.

Uvarov, Alexei V. “Inter- and Intraspecific Interactions in Lumbricid Earthworms: Their Role for Earthworm Performance and Ecosystem Functioning.” Pedobiologia 53, no. 1 (November 2009): 1–27. <https://doi.org/10.1016/j.pedobi.2009.05.001>.

Viles, H. A., L. A. Naylor, N. E. A. Carter, and D. Chaput. “Biogeomorphological Disturbance Regimes: Progress in Linking Ecological and Geomorphological Systems.” Earth Surface Processes and Landforms 33, no. 9 (August 2008): 1419–35. <https://doi.org/10.1002/esp.1717>.

Wilkinson, Marshall T., Paul J. Richards, and Geoff S. Humphreys. “Breaking Ground: Pedological, Geological, and Ecological Implications of Soil Bioturbation.” Earth-Science Reviews 97, no. 1–4 (December 2009): 257–72. <https://doi.org/10.1016/j.earscirev.2009.09.005>.

-   Reviews the implications of biological action in soil / geology.

-   Good table w/ examples of bioturbation. Figure that outlines different kinds of mounding.

Zhang, Yanming, Zhibin Zhang, and Jike Liu. “Burrowing Rodents as Ecosystem Engineers: The Ecology and Management of Plateau Zokors Myospalax Fontanierii in Alpine Meadow Ecosystems on the Tibetan Plateau.” Mammal Review 33, no. 3–4 (September 2003): 284–94. <https://doi.org/10.1046/j.1365-2907.2003.00020.x>.

### Part 2

Gabet, Emmanuel J., O.J. Reichman, and Eric W. Seabloom. “The Effects of Bioturbation on Soil Processes and Sediment Transport.” *Annual Review of Earth and Planetary Sciences* 31, no. 1 (May 2003): 249–73. <https://doi.org/10.1146/annurev.earth.31.100901.141314>.

-   Provides a quantitative framework, an equation, to describe the sediment flux by tree throw—based on tree root depth. Suggest a non-linear relationship between slope angle and sediment flux for creep by tree throw. Relativley independent of curvature.

-   Also, has a small part review of the impacts of various invertebrates (earthworms, ants, termites) and vertebrates (gophers, moles).

Gabet, Emmanuel J. “Gopher Bioturbation: Field Evidence for Non-Linear Hillslope Diffusion.” Earth Surface Processes and Landforms 25, no. 13 (2000): 1419–28. [https://doi.org/10.1002/1096-9837(200012)25:13\<1419::AID-ESP1483.0.CO;2-1](https://doi.org/10.1002/1096-9837(200012)25:13%3c1419::AID-ESP148%3e3.0.CO;2-1).

-   Tests the hypothesis that in hillslope w/ bioturbators, gophers, the relationship between diffusivity and curvature is nonlinear. This is true, the relationship is non-linear, because of preferential transport of surface material downhill. Subsurface material movement was found to have no relationship with hillslope gradient.

-   This paper has some excellent statistics too.

-   An example of lateral actions.

Phillips, Jonathan D. “Changes, Perturbations, and Responses in Geomorphic Systems.” Progress in Physical Geography: Earth and Environment 33, no. 1 (February 2009): 17–30. <https://doi.org/10.1177/0309133309103889>.

-   Promotes a conceptual model for describing geomorphic disturbance considering timescale and branching end-state.

-   Mechanisms are described by… frequency, magnitude, duration, areal extent, speed of onset, spatial dispersion, temporal spacing

-   Landscape responses are described by… response (reaction time and relaxation time), resistance (strength or absorption), resilience, and recursion (feedback).

-   This can be used for conceptual model development.

Meng, Xia, Annemieke M. Kooijman, Arnaud J.A.M. Temme, and Erik L.H. Cammeraat. “The Current and Future Role of Biota in Soil-Landscape Evolution Models.” Earth-Science Reviews 226 (March 2022): 103945. <https://doi.org/10.1016/j.earscirev.2022.103945>.

-   A review of the roles or organisms in soil and landscape evolution. AND a review of the 19 landscape evolution models that contain biota parameters—up to 2020. They conclude that this modeling suite is insufficient for biological organisms. Largely because of a lack of data.

-   Role review is mostly focused on hydrology, soil-bedrock production, weathering, and sediment transport. Lacks discussion of the types of animal activities, and their outcomes.

-   This is a great piece of evidence that animal-soil-landscape modes are underrepresented, and that there is a need both for models and a more holistic understanding.

Baxter, Timothy, Sam Woor, Martin Coombes, and Heather Viles. “The Geomorphic Work of the European Mole (  Talpa europaea  ): Long‐term Monitoring of Molehills Using Structure‐from‐motion Photogrammetry.” Earth Surface Processes and Landforms, October 13, 2024, esp.6008. <https://doi.org/10.1002/esp.6008>.

-   Uses image analysis to study molehills dynamics: how they change over time in shape, size, density, etc. Molehills are very dynamic in location, size density, and change in response to season and introduce variability in soils.

-   Clean review data on mole excavation rates but “difficult to compare because of differences in the design (i.e., time and spatial monitoring scale and method), local conditions (i.e., soil type and climate), reported metrics (i.e., volume vs. mass) and research focus of different studies.”

-   Note about the importance of disturbance regime. Moles reconstruct collapsed burrows. If burrows are frequently collapsed (e.g. by floods or human disturbance), moles will anually excavate more sediment than those in stable landscapes. This poses a challenge for measurement, because we then need both mound abundance and disturbance regime.

-   This is a great case study for lateral, random(?) animal activity.

Cox, G W, and D W Allen. “Soil Translocation by Pocket Gophers in a Mima Moundfield,” 1987.

-   Study on the horizontal and vertical movement of soil on and surrounding pocket gopher mounds. Results suggests a net movement of soils upwards and mound wards, creating larger and larger mounds. Questions remain: How is this opposed by erosion? Is there an equilibrium rate?

-   This is a great example of topography-behavior connections

Darwin, Charles. The Formation of Vegetable Mould through the Action of Worms: With Observations on Their Habits. 1st ed. Cambridge University Press, 1881. <https://doi.org/10.1017/CBO9780511703850>.

-   Obviously, Darwin’s very early work on pedology and bioturbation. He describes how organisms, mostly earthworms, aid in the formation of hillslopes, sort soils and create distinct textural horizons, bury large coarse fragments and ancient buildings, and contribute to the darkening of upper soil horizons.

-   Great paper for the introduction to pedology and bioturbators. Honestly even works as a case study.

Don, Johnson. “BIOMANTLE EVOLUTION AND THE REDISTRIBUTION OF EARTH MATERIALS AND ARTIFACTS.” Soil Science 149, no. 2 (February 1990): 84–102.

-   Early biomantle paper. Similar but a less fleshed out version of the others from 2005. Great figures for tree throw.

-   This I believe is the earliest mention of the biomantle.

Grinnell, Joseph. “THE BURROWING RODENTS OF CALIFORNIA AS AGENTS IN SOIL FORMATION.” JOURNAL OF MAMMALOGY, 1923.

-   Early work on the impacts of gophers on soil development, somewhat parallel to Darwin’s work on earthworms. Mentions the role of organism in mixing soil and in doing so enhancing substratum/soil *chemical* weathering.

-   This a good source for early soils-animals work.

Hansen, R. M. and Morris M. J. “MOVEMENT OF ROCKS BY NORTHERN POCKET GOPHERS.” Journal of Mammalogy 49 (August, 1968): 391-99.

-   Study on the differences in coarse fragment content (fine, 0.64-1.27, 1.27-2.54, and \>2.54cm) of gopher inhabited topsoil, uninhabited topsoil, summer mounds, and winter casts. Author Suggests gophers cannot move fragments \>5cm, average burrow diameter.

-   This is a great sorting case study / hypothesis.

Hartemink, A.E., Y. Zhang, J.G. Bockheim, N. Curi, S.H.G. Silva, J. Grauer-Gray, D.J. Lowe, and P. Krasilnikov. “Soil Horizon Variation: A Review.” In Advances in Agronomy, 160:125–85. Elsevier, 2020. <https://doi.org/10.1016/bs.agron.2019.10.003>.

-   A review of lateral horizon variability. Good figures of tree-throw induced variability.

-   This could be a good lateral variability reference. Need to reed further.

Johnson, D. L., J. E. J. Domier, and D. N. Johnson. “Reflections on the Nature of Soil and Its Biomantle.” Annals of the Association of American Geographers 95, no. 1 (March 1, 2005): 11–31. <https://doi.org/10.1111/j.1467-8306.2005.00448.x>.

AND

Johnson, D.L., J.E.J. Domier, and D.N. Johnson. “Animating the Biodynamics of Soil Thickness Using Process Vector Analysis: A Dynamic Denudation Approach to Soil Formation.” Geomorphology 67, no. 1–2 (April 2005): 23–46. <https://doi.org/10.1016/j.geomorph.2004.08.014>.

-   Companion papers with similar content. Authors propose an alternative, processed based model of soil genesis that greatly emphasizes biological processes

-   Introduces the biomantle, the "skin of the earth", where organisms live, die, and change the soil. Contains a brief history of the other paradigms of soil erosion, dating back to Darwin, Dokuchaev, Hans Jenny, and to more recent USDA scientists.

-   Introduces “bioturbation styles”, great table with upward biotransfers (non-local mixing), biomixing (local mixing), and cratering.

-   Also introduces the dynamic denudation framework, where stonelines develop and serve as permanent restrictive layers in the soil profile.

-   This is a watershed paper in bioturbation literature. Provide several examples of stonelines,

Johnson, D. L., and D. Watson-Stegner. “EVOLUTION MODEL OF PEDOGENESIS:” Soil Science 143, no. 5 (May 1987): 349–66. <https://doi.org/10.1097/00010694-198705000-00005>.

-   Provides a novel framework for soil evolution: one that describe soil as a function of progressive and regressive pedogensis. Progressive pedogensis includes horizonation processes, developmental up-building, and soil deepening. Regressive pedogensis includes haploidization processes, retardant up-building, and soil removal. Development up-building, versus retardant up-building, requires added material be pedogenetically assimilated into the profile. Often this depends on the rate of addition. The authors suggest positive and negative vectors for the following that together drive or oppose soil development.

-   The authors also introduce the idea of internal feedback processes endogenic soil properties dominate over exogenic, environmental factors. For example, a petrocalcic horizon may develop in soil with a Ca rich parent material under an arid climate. This petrocalcic horizon, a product of soil genesis, impacts future development though leaching or bioturbation. A threshold was crossed that put the soil down a unique pedogenetic pathway.

-   The authors also reference Jenny's 1941 clopt model and use that elegant framework to describe their approach of soil genesis. It is a reminder of the utility of that basic equation and it's many applications.

-   Couple references to check out: Yaalon (1971) and Ruellan (1971) soil feedback processes; Wilde (1946, p. 13) include dt in clorpt; Vreeken (1975a) soil landscape processes; Johnson et al. (1987b) dynamic rate model; Runge (1973) and Volobuyeve (1984) thermodyanics of soil end points

Johnson, Michelle O., Simon M. Mudd, Brad Pillans, Nigel A. Spooner, L. Keith Fifield, Mike J. Kirkby, and Manuel Gloor. “Quantifying the Rate and Depth Dependence of Bioturbation Based on Optically‐stimulated Luminescence (OSL) Dates and Meteoric 10 Be.” Earth Surface Processes and Landforms 39, no. 9 (July 2014): 1188–96. <https://doi.org/10.1002/esp.3520>.

Kristensen, Jeppe Aa., Kristina J. Thomsen, Andrew S. Murray, Jan-Pieter Buylaert, Mayank Jain, and Henrik Breuning-Madsen. “Quantification of Termite Bioturbation in a Savannah Ecosystem: Application of OSL Dating.” Quaternary Geochronology 30 (October 2015): 334–41. <https://doi.org/10.1016/j.quageo.2015.02.026>.

-   Uses quarz grains to date the age of a termite mound and soil beneath. I can see there are no bioturbation rate calculations, although this data could be used.

-   Figure 5 of appendix looks visually very similar to what I modeled. my note: note the shape of C is very similar to what is described by a diffusion-advection model (w/ erosion). 100-150cm is the stoneline layer, the lower boundary of bioturbation, and explains the signifigant increase in age after.

-   Sorting case study too

Miller, Milton A. “Burrows of the Sacramento Valley Pocket Gopher in Flood-Irrigated Alfalfa Fields.” Hilgardia 26, no. 8 (January 1957): 431–52. <https://doi.org/10.3733/hilg.v26n08p431>.

-   A dated study on a number of topics, with valuable information on burrow depth and a decent dataset of soil displacement rates by different gopher species.

-   Great figure on burrow area w/ depth.

Nye, P. H. “Some Soil-Forming Processes in the Humid Tropics.” Journal of Soil Science 5, no. 1 (1954): 7–21. <https://doi.org/10.1111/j.1365-2389.1954.tb02171.x>.

Discusses the genesis of a catena of tropical soils in West Africa making reference to the role of soil fauna, here ants, earthworms, and termites, in the creation of stonelines in soils. The author compares the soil texture of termite mounds to that of the suspected termite-formed horizon and finds them similar. He makes notes about coarse fragment size relating to bedrock fracture density and the releative importance of clay illuviation in texture contrast development.

-   This is a good case study for animal sorting.

Román‐Sánchez, Andrea, Ana Laguna, Tony Reimann, Juan Vicente Giráldez, Adolfo Peña, and Tom Vanwalleghem. “Bioturbation and Erosion Rates along the Soil‐hillslope Conveyor Belt, Part 2: Quantification Using an Analytical Solution of the Diffusion–Advection Equation.” Earth Surface Processes and Landforms 44, no. 10 (August 2019): 2066–80. <https://doi.org/10.1002/esp.4626>.

Salvador-Blanes, S., B. Minasny, and A. B. McBratney. “Modelling Long-Term in Situ Soil Profile Evolution: Application to the Genesis of Soil Profiles Containing Stone Layers.” European Journal of Soil Science 58, no. 6 (2007): 1535–48. <https://doi.org/10.1111/j.1365-2389.2007.00961.x>.

Yeates, G. W., and H. Van Der Meulen. “Burial of Soil-Surface Artifacts in the Presence of Lumbricid Earthworms.” Biology and Fertility of Soils 19, no. 1 (January 1995): 73–74. <https://doi.org/10.1007/BF00336350>.

-   Study on the bural of of wire by Lumbricid earthworms in pasture and forest.

-   This is a valuable study focused on non-local mixing.

