# Fallout Radionulcides

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, width = 300, warning = FALSE, out.width = "50%", fig.show = 'hold', fig.align = "center")
library(here)
library(tinytex)
library(ggplot2)
library(dplyr)
library(tidyr)
library(rlang)
library(usethis)
library(bookdown)
library(knitr)
library(rmarkdown)
library(spelling)
```

## Background: Sampling

Measurement of 137Cs and 210Pb inventories is a well-established method of measuring erosion, bioturbation, and sediment transport. They represent a relatively fieldwork-light, although technical, approach to measuring soil erosion across decade to century timescales. The core of the method is comparing 137Cs and/or 210Pb inventories between samples taken at erosional/depositional sites and an undisturbed reference site. Samples with a lesser inventory than the reference site reflect erosion, and cores with a greater inventory reflect deposition.

The International Atomic Energy Agency provides general guidelines for 137Cs and 210Pb use in “Guidelines for using fallout radionuclides to assess erosion and effectiveness of soil conservation strategies” 2014. In short, this method involves A) sampling an undisturbed reference site and an erosional/depositional site, B) preprocessing and analyzing samples for 137Cs and 210OPb activity in a lab on a germanium detector, and C) employing a model to convert radioisotope inventories to erosion rates. The application of this method depends on three assumptions on the behavior of these radioisotopes in the environment (IAEA, 2014):

1.  137Cs and 210Pb are spatially uniform across the study area.

2.  137Cs and 210Pb are rapidly and irreversibly absorbed to soil particles, limiting their movement to physical transport.

3.  137Cs and 210Pb depth distributions are equivalent, excluding physical movement of soil particles, between reference and sample sites

However, as many authors explore, these assumptions are imperfect and demand the user consider multiple potential sources of error (Baccolo et al., 2023; Nolin et al., 1993; Parsons & Foster, 2011; Mabit et al., 2013). Following is a discussion of ‘areas of concern’ and how they are addressed in the literature and in review:

-   Reference site selection

-   Reference site sampling

-   Erosion sample position

-   Erosion site sampling

-   Erosion sample positioning

-   Sample characteristics

-   Bioturbation and nuclide distribution

-   Reference site selection

Reference site selection can be challenging, especially in study areas with unknown or highly variable land use. The IAEA guidelines provide the following criteria for reference site selection: the site should be 1) undisturbed and under consistent land-use since 1950, 2) within \~1 km of the sample area, and 3) not experiencing erosion or deposition. Hancock et al. 2008, additionally suggests selecting a reference site where precipitation, the driving factor of 137Cs/excess 210Pb deposition (IAEA, 2014), is expected to be similar to the erosional/depositional area. Additionally, if the reference site is in a forest, a larger number of cores should be taken to account for greater heterogeneity (IAEA, 2014). Cores should also be taken avoiding trees and areas of concentrated stemflow (Nolin et al., 1993).

[Reference site sampling]{.underline}

The assumption of an even distribution of fallout across the landscape is limited by several sources of small-scale variability. These include spatial differences in the soil properties that control 137Cs absorption, interception of depositional rainfall by vegetation, uptake of radioisotopes by plants, and animal or human disturbance (IAEA, 2014; Parsons & Foster, 2011; Mabit et al., 2013). To broadly account for this variability, taking replicate cores across the reference site is widely applied. The IAEA guidelines recommend a minimum of 10 - 15 samples per reference site. For a forested site, Nolin et al. 1993 provides equations to estimate the number of samples needed to achieve a specific allowable error and confidence level.

However, analyzing 10 – 15 samples can be expensive and time consuming, so many studies bulk reference cores after segmentation to reduce the number of samples to analyze (Arata et al., 2016; Baccolo et al., 2023; Hancock et al., 2008; Nolin et al., 1993). Bulking is also suggested by the IAEA. The downside to bulking samples, however, is the loss of data on the variability of radioisotope inventories across the reference site. Cost, time, and statistical rigor must all be considered when deciding to bulk or not bulk samples.

[Erosion sample positioning]{.underline}

Placement of cores along a hillslope is important to consider before sampling. The IAEA suggests, for a slope with minimal horizontal complexity, a minimum of 3 equally spaced samples along a transect. This is a common approach in the literature, followed by Elliott et al., 1989; Hancock et al., 2008; Nolin et al., 1993; and Wallbrink & Murray, 1996. For more complex slopes, additional cores from additional transects should be taken, but both strategies are compatible with most currently available inventory conversion models (IAEA, 2014). Additionally, there are newer models that allow for greater flexibility in sampling strategy and have demonstrated success under a variety of conditions (Baccolo et al., 2023; Arata et al., 2016). Given relatively equal core spacing along a transect, it also is worth considering what is being measured at each point: e.g. the magnitude of erosion and/or deposition. Elliott et al., 1989, provides a theoretical model for this, depicted below. However, this is dependent on the purpose of the study.

[Erosion site sampling]{.underline}

Accounting for small-scale variability is also important for erosion site sampling, but there is disagreement in the literature about sample numbers. It is relatively common to collect 1 - 5 soil cores at each erosion sampling point (Arata et al., 2016; Baccolo et al., 2023; Hancock et al., 2008; Nolin et al., 1993). This is also in agreement with the IAEA guidelines. However, Parsons & Foster 2011 raises the point that the small-scale variability in 137Cs distribution is not exclusive to the reference site, and that a similar number of replicates, 10 - 15, should be taken from each sampling point. Jarvis et al., 2010 employs this larger number of samples per site, although the focus of that study is not soil erosion. It is worth noting, the above studies with smaller core numbers do present compelling data, and some with comparable measurements by other methods.

[Sample characteristics]{.underline}

Finally, it is important to consider the characteristics of individual cores and samples (cores after bulking or segmenting, final products to be analyzed). For both reference and erosion sites, core depth and radius are important to consider. The IAEA provides guidelines for both. The standard recommendation is a corer diameter of 7 – 10 cm and a total depth of 30cm for reference and erosional sites and 40 – 60 cm for depositional sites. For the most part, this is consistent in the literature (Elliott et al., 1989; Hancock et al., 2008; Nolin et al., 1993; Baccolo et al., 2023; Arata et al., 2016; and Wallbrink & Murray, 1996). However, when many replicates are being taken and bulked, one may consider using a corer of a smaller diameter. Minimizing sample volume makes easier sample processing and more consistent homogenization (Nate Lund, personal observation).

In addition, for reference sites, the size of reference core segments is another consideration. Reference cores are segmented for three reasons: (1) to establish the reference inventory, (2) determine the depth profile of 137Cs and 210Pb (necessary for conversion models), and (3) determine the maximum depth of 137Cs and 210Pb activity to inform sampling depth (IAEA, 2014). The IAEA broadly recommends 2 – 5 cm. Smaller segments provide a more detailed activity-depth profile, but require more samples be analyzed.

[Bioturbation and nuclide distribution]{.underline}

Earthworm bioturbation is important factor to consider when converting from radioisotope inventories to erosion and deposition rates. Literature shows that earthworms have a significant impact on the 137Cs distribution in the profile—flattening the exponential decay expected under natural conditions (Jarvis et al., 2010; Tyler et al., 2001; VandenBygaart et al., 1998). VandenBygaart et al., 1998, also suggests a relationship between earthworm abundance and 137Cs redistribution. The consequences of this redistribution are twofold. One, bioturbation by deep-burrowing Lumbricus terrestris may extend the depth of 137Cs distribution beyond 30cm and require deeper sampling. Two, continuous mixing dilutes 137Cs concentration in eroding sediments, which without correction, may result in an underestimation of erosion rates.
