# Laser Scanner

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, width = 300, warning = FALSE, out.width = "50%", fig.show = 'hold', fig.align = "center")
library(here)
library(tinytex)
library(ggplot2)
library(dplyr)
library(tidyr)
library(rlang)
library(usethis)
library(bookdown)
library(knitr)
library(rmarkdown)
library(spelling)
```

## Data

Temporary home: <https://drive.google.com/drive/folders/1ZYsJej_rGxnZyThFrdr3AuWrt8Xvgb4f?usp=drive_link>

## Notes to self

-   Traveling with the scanner. Scanner can be traveled with easily. Check scanner box and duffel bag with tripods. Batter is okay to be checked. Cary on camera.

-   Data download. To download data, power on and insert formatted (?) USB drive. Navigate to Settings \> File Browser. Mark all the needed files. Press Action \> Copy \> Media (switch to usb) \> Insert \> Ok. Remove drive and insert into computer.

-   Software. GoldenSoftwareSurfer (demo) eases transforming from point clouds to 2D grids. Can likely get a license from Steve.

## Collecting data

Before turning scanner on, make sure the camera is connected and also on (if using).

*Camera calibration settings.*

Before collecting data, make sure to: create a new project, turn Scanpos auto ON, and select the correct pattern. Note, if the position does not update between scans, it is basically impossible to separate the two. The patterns we use are:

-   For normal scans - Pattern.50 (2 minute scan)

-   For higher resolution - Pattern.30 (5 minute scan)
