# Vegetation Analysis

```{r setup, include=FALSE}
# chunk options
knitr::opts_chunk$set(eval = FALSE, echo = TRUE, width = 300, warning = FALSE, out.width = "45%", fig.show = 'hold', fig.align = "center")

# libraries needed
libs <- c("tinytex", "ggplot2", "dplyr", "tidyr", "rlang", "usethis", "bookdown", "knitr", "rmarkdown", "spelling", "lidR", "shapefiles", "sf", "terra", "raster", "ggplot2", "easypackages", "spatialEco", "rasterVis")

# install missing libraries
installed_libs <- libs %in% rownames(installed.packages())
if (any(installed_libs == F)) {
  install.packages(libs[!installed_libs])
}

# load libraries
lapply(libs, library, character.only = T)
```

Load image and prep data frames.

```{r}
#set wd
setwd("C:/Users/natha/Documents/local_data/_data/_terrestrial_lidar")


```

Color by index

```{r}
######################### code for a single image #########################

# Rasterfy the image
image <- brick(x = "C:/Users/natha/Documents/local_data/_data/_terrestrial_lidar/test_image.jpg")

# Extract red, blue and green bands to unique raster files
red <- image[[1]]
green <- image[[2]]
blue <- image[[3]]

# Calculate index raster
index <- 2 * (green) - red - blue

#force index raster to be read as a data frame (needed for ggplot)
index_spdf <- as(index, "SpatialPixelsDataFrame")
index_df <- as.data.frame(index_spdf)
#give index_df proper column names
colnames(index_df) <- c("value", "x", "y")

#filter index for just for veg 
index_veg = index_df %>%
  filter(value > 50) # this value is subjective, need to figure out

print(nrow(index_veg) / 12000000)
```



```{r}
######################### visualization #########################

#histogram of index value distributions
ggplot(data = index_df, aes(x = value)) +
  geom_histogram(binwidth = 1)
  #scale_x_continuous(limits = c(-5,100))

plot(image)

# Plot the full index
ggplot(data = index_df, aes(x = x, y = y, fill = value)) +
  geom_tile()

# Plot the filtered index_veg
ggplot(data = index_veg, aes(x = x, y = y, fill = value)) +
  geom_tile()
```

```{r}
######################### code for baching (defunct) #########################

#beginning for loop
for(current_file in files) {
  #creates a complete file path for use in
    working_image = paste(file_path, current_file, sep = "")
  #create a three-layer raster for working image
    image <- brick(x = working_image)
  # Extract red, blue and green bands to unique raster files
    red <- image[[1]]
    green <- image[[2]]
    blue <- image[[3]]
  # Calculate index raster
    index <- 2 * (green) - red - blue
  #force index raster to be read as a data frame (needed for ggplot)
    index_spdf <- as(index, "SpatialPixelsDataFrame")
    index_df <- as.data.frame(index_spdf)
      #give index_df proper column names
         colnames(index_df) <- c("value", "x", "y")
  #filter index for just for veg
    index_veg = index_df %>% 
      filter(value > 75)
  #write the filtered count to a row in final_df
    final_df[current_file,] = nrow(index_veg) / 12000000
    print(nrow(index_veg)/ 12000000)
  }

head(final_df)

#trim columns, change x to numeric, and add a summary group based on 3
export_df_2 = transform(final_df, x = as.numeric(x))
export_df = dplyr::select(export_df_2, "x")
export_df$t = rep(c(1, 2, 3, 5, 6, 7, 8, 9, 11, 12, 13, 14), each = 3)

#create summary table for each 3-picture set 
export_csv = export_df %>% 
  group_by(t) %>% 
  summarize(mean_veg = mean(x))
export_csv

#export csv to folder
write.csv(x = export_csv, file = output_name)

```